/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PitchRollCorrections.app;

import PitchRollCorrections.list.LinkedList;


public class App {
    public static void main(String[] args) {

    }
}
